# Generated by Django 5.1.5 on 2026-02-11 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_userbalance_price_per_change_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertraders',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 11, 12, 31, 30, 169395, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.date(2026, 2, 11), verbose_name='Дата последнего входа'),
        ),
    ]
