# Generated by Django 5.1.5 on 2026-03-10 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_usertraders_total_alter_teamstats_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalance',
            name='count_of_friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='count_of_share_invite_link',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='money_which_i_donate',
            field=models.FloatField(default=0, verbose_name='Деньгии которые я задонатил'),
        ),
        migrations.AlterField(
            model_name='teamstats',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 8, 34, 36, 469344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateField(default=datetime.date(2026, 3, 10), verbose_name='Дата последнего входа'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='token_money',
            field=models.FloatField(default=0, verbose_name='Общий баланс донатной валюты'),
        ),
    ]
