# Generated by Django 5.2.17 on 2026-09-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_dynamic_date_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofice',
            name='safe_capacity_per_trader',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traders',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='token_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Общий баланс донатной валюты'),
        ),
    ]
