# Generated by Django 5.2.17 on 2026-09-24 14:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_team_snapshot_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='welcome', max_length=16)),
                ('step', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='OperationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('signature', models.CharField(max_length=180)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_player_operation_key')],
            },
        ),
        migrations.CreateModel(
            name='TaskReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('kind', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ready_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(null=True)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_rewards', to='main.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_player_task_reward')],
            },
        ),
    ]
